/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bo.usfx.sis457.catalogopeliculasmvc.vistas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcelo
 */
public class JPanelCategoriasListar extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCategorias
     */
    public JPanelCategoriasListar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarCategorias = new javax.swing.JToolBar();
        jButtonNuevo = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonActualizar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelBusqueda = new javax.swing.JLabel();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jButtonBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCategorias = new javax.swing.JTable();
        jLabelTotalRegistros = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();

        jToolBarCategorias.setFloatable(false);
        jToolBarCategorias.setRollover(true);

        jButtonNuevo.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bo/usfx/sis457/catalogopeliculasmvc/resources/botones/nuevo.png"))); // NOI18N
        jButtonNuevo.setText("Nueva");
        jButtonNuevo.setFocusable(false);
        jButtonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevo.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonNuevo.setMaximumSize(new java.awt.Dimension(80, 60));
        jButtonNuevo.setMinimumSize(new java.awt.Dimension(80, 60));
        jButtonNuevo.setPreferredSize(new java.awt.Dimension(80, 40));
        jButtonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarCategorias.add(jButtonNuevo);

        jButtonModificar.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bo/usfx/sis457/catalogopeliculasmvc/resources/botones/modificar.png"))); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.setFocusable(false);
        jButtonModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonModificar.setMaximumSize(new java.awt.Dimension(80, 60));
        jButtonModificar.setMinimumSize(new java.awt.Dimension(80, 60));
        jButtonModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarCategorias.add(jButtonModificar);

        jButtonBorrar.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jButtonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bo/usfx/sis457/catalogopeliculasmvc/resources/botones/borrar.png"))); // NOI18N
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.setFocusable(false);
        jButtonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBorrar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonBorrar.setMaximumSize(new java.awt.Dimension(80, 60));
        jButtonBorrar.setMinimumSize(new java.awt.Dimension(80, 60));
        jButtonBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarCategorias.add(jButtonBorrar);
        jToolBarCategorias.add(jSeparator1);

        jButtonActualizar.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bo/usfx/sis457/catalogopeliculasmvc/resources/botones/actualizar.png"))); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.setFocusable(false);
        jButtonActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonActualizar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonActualizar.setMaximumSize(new java.awt.Dimension(80, 60));
        jButtonActualizar.setMinimumSize(new java.awt.Dimension(80, 60));
        jButtonActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarCategorias.add(jButtonActualizar);

        jLabelTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelTitulo.setText("Gestionar Categorías");

        jLabelBusqueda.setText(" Introduzca un texto a buscar");

        jButtonBusqueda.setText("Buscar");

        jTableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCategorias);

        jLabelTotalRegistros.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTotalRegistros.setText("Total Registros: 100");

        jButtonLimpiar.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jToolBarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBusqueda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimpiar)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addComponent(jLabelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBusqueda)
                            .addComponent(jButtonLimpiar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTotalRegistros)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBusqueda;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JLabel jLabelBusqueda;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotalRegistros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTableCategorias;
    private javax.swing.JTextField jTextFieldBusqueda;
    private javax.swing.JToolBar jToolBarCategorias;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getJButtonNuevo() {
        return jButtonNuevo;
    }
    
    public javax.swing.JButton getJButtonModificar() {
        return jButtonModificar;
    }
    
    public javax.swing.JButton getJButtonBorrar() {
        return jButtonBorrar;
    }
    
    public javax.swing.JButton getJButtonActualizar() {
        return jButtonActualizar;
    }
    
    public javax.swing.JTextField getJTextFieldBusqueda() {
        return jTextFieldBusqueda;
    }
    
    public javax.swing.JButton getJButtonBusqueda() {
        return jButtonBusqueda;
    }
    
    public javax.swing.JButton getJButtonLimpiar() {
        return jButtonLimpiar;
    }
    
    public javax.swing.JTable getJTableCategorias() {
        return jTableCategorias;
    }
    
    public void setDatos(DefaultTableModel modeloTabla, int total) {
        jTableCategorias.setModel(modeloTabla);
        jLabelTotalRegistros.setText("Total Registros: " + total);
    }
    
    
}
